# Generated by Django 4.2.6 on 2023-11-04 10:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='sent_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='SentNewsletterEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('sent_successfully', models.BooleanField(default=False)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.newsletter')),
            ],
        ),
    ]
