# Generated by Django 4.2.6 on 2023-11-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_newsletter_sent_date_sentnewsletteremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='recipients',
            field=models.TextField(default='', help_text='Comma-separated list of recipient emails'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='sent_successfully',
            field=models.TextField(default='', help_text='Comma-separated list of successfully sent emails'),
        ),
        migrations.DeleteModel(
            name='SentNewsletterEmail',
        ),
    ]
